CFLAGS = -Wall -Wextra -pedantic-errors
CC=cc

all: exercise_1 exercise_2 exercise_3 exercise_4 exercise_5 exercise_6 exercise_7 exercise_8 
exercise_1:
exercise_2:
exercise_3:
exercise_4:
exercise_5:
exercise_6:
exercise_7:
exercise_8:

clean:
	rm exercise_1 exercise_2 exercise_3 exercise_4 exercise_5 exercise_6 exercise_7 exercise_8
